server:
  #al colocar 0 le indicamos que el entorno donde esta alojado el ms que busque la lista puertos libre, y le asignara aleatoriamente un puerto libre
  port: ${PORT:${SERVER_PORT:0}}

#configuramos el cliente de Eureka
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    #hostname: localhost

#configuramos la ubicacion y acceso a la base de datos
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/bd_service_bike
    username: root
    password: 
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#configurar JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
