server:
  port: 8022

#configuramos la ubicacion y acceso a la base de datos
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/bd_service_bike
    username: root
    password: 
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#configurar JPA
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update