server:
  port: 8080

#configuramos el cliente de Eureka
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

#configurando las ruta de los microservicios
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
          - Path=/usr/**
        - id: car-service
          uri: lb://car-service
          predicates:
          - Path=/cr/**
        - id: bike-service
          uri: lb://bike-service
          predicates:
          - Path=/bk/**