server:
  port: 9000

#configuramos el cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#configurando las ruta de los microservicios
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
          - Path=/usr/**
        - id: car-service
          uri: lb://car-service
          predicates:
          - Path=/cr/**
        - id: bike-service
          uri: lb://bike-service
          predicates:
          - Path=/bk/**